/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package Ants

import com.badlogic.gdx.Gdx
import com.badlogic.gdx.graphics.Pixmap
import com.badlogic.gdx.graphics.Texture
import com.badlogic.gdx.utils.GdxNativesLoader
import me.apemanzilla.ktcl.cl10.createCommandQueue
import me.apemanzilla.ktcl.cl10.createContext
import me.apemanzilla.ktcl.cl10.getDefaultDevice
import me.apemanzilla.ktcl.cl10.getPlatforms
import me.zakharov.me.zakharov.Ground
import kotlin.test.Test

class AntsTest {
    init {
        GdxNativesLoader.load();
    }
    @Test fun singleAntScanning() {
        val device = getPlatforms()[0].getDefaultDevice()!!
        val ctx = device.createContext()
        val cmd = device.createCommandQueue(ctx)
        //create ground texture
        //assert(Gdx.gl != null) { "no gl context" }
        //val emptyGround = Texture(Pixmap(10, 10, Pixmap.Format.RGBA8888))
        //val ground = Ground(emptyGround, ctx, cmd, 10, 10)

    }
}
